1. Import thư viện

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
from pathlib import Path
import pandas as pd

2. Converting text using TF-IDF

In [ ]:
def find_project_root(start_path: Path) -> Path:
    current = start_path.resolve()
    for p in [current] + list(current.parents):
        if (p / "data").exists():
            return p
    return current


project_root = find_project_root(Path.cwd())
corpus_path = project_root / "data" / "processed" / "corpus_raw.txt"

if not corpus_path.exists():
    raise FileNotFoundError(
        f"Khong tim thay file corpus: {corpus_path}."
    )


def corpus_generator(file_path: Path):
    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                yield line


print(f"Bat dau xu ly file: {corpus_path.name}")
print("Dang khoi tao ...")

vectorizer = TfidfVectorizer()

print("Dang ma hoa du lieu...")
corpus_list = list(corpus_generator(corpus_path))
X_encoded = vectorizer.fit_transform(corpus_list) 

print("\n--- KET QUA ---")
df = pd.DataFrame(X_encoded.toarray(), columns=vectorizer.get_feature_names_out(), index = corpus_list)
df.head()

Bat dau xu ly file: corpus_raw.txt
Dang khoi tao ...
Dang ma hoa du lieu...

--- KET QUA ---

,01,02,03,05,08,09,10,100,1000,11,...,ước,ảnh_hưởng,ấp,ồn,ồn_phương_tiện,ổn_định,ủy,ủy_ban_nhân_dân,ủy_thác,ứng_dụng
công báo 983 984 2582024 3 quốc_hội cộng_hòa xã_hội_chủ_nghĩa_việt_nam độc_lập tự hạnh_phúc luật 35 2024 quốc_hội khóa 15 luật đường_bộ căn_cứ hiến_pháp nước cộng_hòa xã_hội_chủ_nghĩa_việt_nam quốc_hội ban_hành luật đường_bộ i quy_định chung 1 phạm_vi chỉnh_luật quy_định hoạt_động đường_bộ quản_lý_nhà_nước hoạt_động đường_bộ 2 giải_thích_ngữ luật_ngữ hiểu 1 hoạt_động đường_bộ hoạt_động quy_hoạch đầu_tư xây_dựng quản_lý sử_dụng vận_hành khai_thác bảo_trì bảo_vệ kết_cấu_hạ_tầng đường_bộ vận_tải đường_bộ 2 đường_bộ đường cầu_đường_bộ cống đường_bộ hầm đường_bộ bến phà đường_bộ cầu_phao đường_bộ đường cứu nạn công_trình phụ_trợ gắn liền đường_bộ 3 công_trình đường_bộ đường_bộ công_trình phục_vụ công_tác quản_lý vận_hành khai_thác đường_bộ công_trình hệ_thống quản_lý giao_thông thông_minh nhà hạt quản_lý đường_bộ kho chứa trang_thiết vật_tư dự_phòng lĩnh_vực đường_bộ công_trình kiểm_soát tải_trọng xe trạm thu phí công_trình đường_bộ 4 kết_cấu_hạ_tầng đường_bộ công_trình đường_bộ bến_xe bãi đỗ xe trạm dừng nghỉ dừng xe đỗ xe đất đường_bộ hành_lang_an đường_bộ công_trình phụ_trợ phục_vụ hoạt_động đường_bộ 5 hành_lang_an đường_bộ dải đất dọc hai đất đường_bộ tính mép ngoài phần đất bảo_vệ bảo_trì đường_bộ hai bảo_đảm an giao,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000
4 công báo 983 984 2582024 thông đường_bộ bảo_đảm tầm nhìn xe chạy hạn_chế ảnh_hưởng môi_trường xung_quanh 6 cơ_quan quản_lý đường_bộ cơ_quan bộ giao_thông vận_tải giúp bộ_trưởng bộ giao_thông vận_tải thực_hiện chức_năng quản_lý_nhà_nước hoạt_động đường_bộ cơ_quan_chuyên_môn ủy ban_nhân_dân cấp tỉnh cơ_quan_chuyên_môn ủy ban_nhân_dân cấp huyện ủy_ban_nhân_dân cấp xã 7 quản_lý sử_dụng đường_bộ chủ_sở_hữu trực_tiếp quản_lý sử_dụng vận_hành khai_thác công_trình đường_bộ tổ_chức cá_nhân giao quản_lý sử_dụng vận_hành khai_thác công_trình đường_bộ 3 nguyên_tắc hoạt_động đường_bộ 1 bảo_đảm giao_thông thông_an kết_nối đồng_bộ hiệu_quả thân_thiện môi_trường phục_vụ nhu_cầu vận_tải hàng hóa thuận_tiện dân góp_phần phát_triển kinh_tế xã_hội bảo_đảm quốc_phòng an_ninh bảo_vệ môi_trường phòng_chống thiên_tai hội_nhập quốc_tế 2 phát_triển đường_bộ quy_hoạch sử_dụng hiệu_quả nguồn_lực kết_nối phương_thức vận_tải đường_bộ phương_thức vận_tải tăng_cường ứng_dụng khoa_học công_nghệ tiên_tiến bảo_đảm văn_minh hiện_đại đồng_bộ 3 thực_hiện thống_nhất cơ_sở phân_công phân_cấp trách_nhiệm quyền_hạn cụ đồng_thời sự phối_hợp chặt_chẽ bộ_ngành quyền địa_phương cấp 4 mọi hành_vi vi_phạm pháp_luật hoạt_động đường_bộ phát_hiện ngăn_chặn kịp_thời xử_lý nghiêm_minh pháp_luật 4 sách phát_triển đối_hoạt_động đường_bộ 1 sách phát_triển kết_cấu_hạ_tầng đường_bộ a tập_trung nguồn_lực phát_triển kết_cấu_hạ_tầng đường_bộ hiện_đại thích_ứng_biến_đổi khí_hậu thân_thiện môi_trường kết_nối đồng_bộ tuyến đường_bộ phương_thức vận_tải vận_tải đường_bộ b xây_dựng cơ_chế đẩy_mạnh huy_động nguồn_lực xã_hội đa_dạng hình_thức phương_thức đầu_tư xây_dựng quản_lý vận_hành khai_thác bảo_trì kết_cấu_hạ_tầng đường_bộ c ưu_tiên phát_triển tuyến đường_cao_tốc công_trình dự_án đường_bộ trọng_kết_nối vùng khu_vực đô_thị lớn trung_tâm nước quốc_tế kết_cấu_hạ_tầng đường_bộ vùng đồng_bào dân_tộc_thiểu miền núi hải_đảo biên_giới,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.041833,0.0,0.0,0.0,0.0,0.081802,0.075345,0.0,0.055399
công báo 983 984 2582024 5 kết_cấu_hạ_tầng đường_bộ dễ tiếp_cận bảo_đảm an đối_tượng dễ tổn_thương kết_cấu_hạ_tầng đường_bộ đô_thị giảm ùn_tắc giao_thông tuyến đường tuần_tra biên_giới đường ven biển phục_vụ tiêu kết_hợp phát_triển kinh_tế xã_hội bảo_đảm quốc_phòng an_ninh 2 phát_triển hợp_lý loại_hình kinh_doanh vận_tải tạo môi_trường cạnh_tranh lành_mạnh loại_hình kinh_doanh vận_tải xe ô_tô phát_triển giao_thông thông_minh ưu_tiên phát_triển vận_tải hành_khách công_cộng xe_buýt phương_tiện vận_tải 3 khuyến_khích tạo kiện tổ_chức cá_nhân việt_nam nước_ngoài đầu_tư kinh_doanh khai_thác kết_cấu_hạ_tầng đường_bộ hoạt_động vận_tải đường_bộ nghiên_cứu ứng_dụng khoa_học công_nghệ tiên_tiến vật_liệu bền_vững thân_thiện môi_trường đào_tạo nguồn nhân_lực lĩnh_vực đường_bộ 5 quy_hoạch mạng_lưới đường_bộ quy_hoạch kết_cấu_hạ_tầng đường_bộ 1 quy_hoạch mạng_lưới đường_bộ quy_định a quy_hoạch mạng_lưới đường_bộ quy_hoạch ngành quốc_gia xác_định phương_hướng phát_triển tổ_chức gian hệ_thống quốc_lộ làm cơ_sở định_hướng lập quy_hoạch kết_cấu_hạ_tầng đường_bộ phát_triển mạng_lưới đường_bộ b lập thẩm_định phê_duyệt chỉnh quy_hoạch mạng_lưới đường_bộ tuân_thủ quy_định pháp_luật quy_hoạch bảo_đảm kết_nối phương_thức vận_tải đường_bộ phương_thức vận_tải c_bộ giao_thông vận_tải tổ_chức lập quy_hoạch mạng_lưới đường_bộ trình thủ_tướng phủ phê_duyệt 2 quy_hoạch kết_cấu_hạ_tầng đường_bộ quy_định a quy_hoạch kết_cấu_hạ_tầng đường_bộ quy_hoạch tính_chất kỹ_thuật chuyên_ngành cụ hóa quy_hoạch mạng_lưới đường_bộ xác_định phương_án phát_triển công_trình đường_bộ kết_cấu_hạ_tầng đường_bộ tuyến đường_bộ b quy_hoạch kết_cấu_hạ_tầng đường_bộ nội_dung chủ_yếu xác_định hướng tuyến cơ_bản khống_chế chiều dài quy_mô tuyến đường_bộ địa_phương vùng xác_định sơ_bộ quy_mô cầu hầm bến phà tuyến đường_bộ xác_định giao_cắt phương_án kết_nối đường_bộ phương_thức vận_tải kết_nối hệ_thống đô_thị khu kinh_tế khu công_nghiệp xác_định nhu_cầu sử_dụng đất nhu_cầu vốn đầu_tư lộ_trình thực_hiện quy_hoạch giải_pháp thực_hiện quy_hoạch,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.041464
6 công_báo 983 984 2582024 c_bộ giao_thông vận_tải tổ_chức lập quy_hoạch kết_cấu_hạ_tầng đường_bộ trình thủ_tướng phủ phê_duyệt 3 thời_kỳ quy_hoạch kết_cấu_hạ_tầng đường_bộ 10 tầm nhìn 20 30 quy_hoạch kết_cấu_hạ_tầng đường_bộ rà_soát định_kỳ 05 chỉnh phù_hợp tình_hình phát_triển kinh_tế xã_hội giai_đoạn công_bố công_khai 4 ủy ban_nhân_dân cấp tỉnh tổ_chức lập nội_dung phát_triển đường_bộ phương_án phát_triển mạng_lưới giao_thông quy_hoạch quy_định pháp_luật quy_hoạch quy_định pháp_luật liên_quan nội_dung phát_triển đường_bộ đô_thị xác_định quy_hoạch quy_định pháp_luật quy_hoạch_đô_thị quy_định pháp_luật liên_quan 5 quy_hoạch quy_định bảo_đảm quy_định a kết_nối giao_thông đường_bộ đô_thị địa_bàn khu_vực bến_xe b kết_nối hiệu_quả phương_thức vận_tải xác_định tuyến đường_bộ nối cửa_khẩu quốc_tế cửa_khẩu ga đường_sắt cảng_hàng cảng biển cảng cạn cảng thủy nội_địa 6 phủ quy_định chi_tiết nội_dung trình_tự thủ_tục lập thẩm_định phê_duyệt chỉnh quy_hoạch kết_cấu_hạ_tầng đường_bộ 6 cơ_sở_dữ_liệu đường_bộ 1 cơ_sở_dữ_liệu đường_bộ thiết_kế xây_dựng vận_hành khung kiến_trúc tổng quốc_gia a cơ_sở_dữ_liệu quy_hoạch mạng_lưới đường_bộ quy_hoạch kết_cấu_hạ_tầng đường_bộ b cơ_sở_dữ_liệu tình_hình đầu_tư xây_dựng kết_cấu_hạ_tầng đường_bộ c cơ_sở_dữ_liệu kết_cấu_hạ_tầng đường_bộ đưa khai_thác d cơ_sở_dữ_liệu thanh_toán điện_tử giao_thông đường_bộ đ cơ_sở_dữ_liệu hoạt_động vận_tải xe ô_tô trừ cơ_sở_dữ_liệu hành_trình phương_tiện giao_thông đường_bộ hình_ảnh lái_xe cơ_sở_dữ_liệu quản_lý thời_gian khiển phương_tiện lái_xe quy_định pháp_luật 2 cơ_sở_dữ_liệu đường_bộ kết_nối chia_sẻ cơ_sở_dữ_liệu trật_tự an giao_thông đường_bộ cơ_sở_dữ_liệu liên_quan,0.0,0.0,0.0,0.065446,0.0,0.0,0.045529,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.032365,0.000000,0.0,0.000000
công báo 983 984 2582024 7 3 phủ quy_định chi_tiết 1 2 quy_định thu_thập quản_lý khai_thác thông_tin cơ_sở_dữ_liệu đường_bộ 7 hành_vi nghiêm_cấm 1 phá_hoại kết_cấu_hạ_tầng đường_bộ khai_thác sử_dụng kết_cấu_hạ_tầng đường_bộ trái quy_định pháp_luật 2 đấu_nối trái_phép đường_đường nhánh tháo_dỡ di_chuyển trái_phép làm sai_lệch công_trình đường_bộ 3 lấn_chiếm sử_dụng xây_dựng trái_phép phạm_vi bảo_vệ kết_cấu_hạ_tầng đường_bộ 4 lắp_đặt tháo_dỡ di_chuyển chỉnh che_khuất báo_hiệu đường_bộ trái quy_định pháp_luật gắn treo lắp báo_hiệu đường_bộ nội_dung liên_quan ý_nghĩa đích_báo_hiệu đường_bộ làm sai_lệch báo_hiệu đường_bộ 5 kinh_doanh vận_tải xe ô_tô xe bốn bánh gắn động_cơ giấy_phép kinh_doanh vận_tải quy_định pháp_luật kinh_doanh giấy_phép 6 lập đón trả khách bốc_dỡ hàng hóa trái quy_định pháp_luật ii kết_cấu_hạ_tầng đường_bộ 1 phân_loại đặt tên hiệu đường_bộ 8 phân_loại đường_bộ cấp quản_lý 1 đường_bộ cấp quản_lý quốc_lộ đường tỉnh đường huyện đường xã đường thôn đường đô_thị đường chuyên_dùng xác_định a_quốc_lộ đường nối_liền thủ_đô hà_nội trung_tâm hành_cấp tỉnh đường nối_liền trung_tâm hành_cấp tỉnh đường vị_trí quan_trọng đối_sự phát_triển kinh_tế xã_hội bảo_đảm quốc_phòng an_ninh vùng khu_vực b đường tỉnh đường nằm địa_bàn tỉnh nối trung_tâm hành tỉnh trung_tâm hành huyện đường vị_trí quan_trọng đối_sự phát_triển kinh_tế xã_hội tỉnh c đường huyện đường_nối trung_tâm hành huyện trung_tâm hành_xã cụm xã trung_tâm hành huyện lân_cận đường vị_trí quan_trọng đối_sự phát_triển kinh_tế xã_hội huyện,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000

In [17]:
project_root = find_project_root(Path.cwd())
corpus_path_2 = project_root / "data" / "processed" / "corpus_raw_2.txt"

if not corpus_path_2.exists():
    raise FileNotFoundError(
        f"Khong tim thay file corpus: {corpus_path_2}."
    )

print(f"Bat dau xu ly file: {corpus_path_2.name}")
print("Dang khoi tao ...")

vectorizer = TfidfVectorizer()

print("Dang ma hoa du lieu...")
corpus_list_2 = list(corpus_generator(corpus_path_2))
X_encoded_2 = vectorizer.fit_transform(corpus_list_2) 

print("\n--- KET QUA ---")
df2 = pd.DataFrame(X_encoded_2.toarray(), columns=vectorizer.get_feature_names_out(), index = corpus_list_2)
df2.head()

Bat dau xu ly file: corpus_raw_2.txt
Dang khoi tao ...
Dang ma hoa du lieu...

--- KET QUA ---

,01,02,025,03,04,05,06,08,10,100,...,đứng_tên,đựng,ưu_tiên,ảnh_hưởng,ồn,ồn_bụi,ủy,ủy_ban,ủy_quyền,ứng_dụng
phủ cộng_hòa xã_hội_chủ_nghĩa_việt_nam độc_lập tự hạnh_phúc 168 2024 nđcp hà_nội 26 12 2024 nghị_định quy_định xử_phạt vi_phạm hành_trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ trừ phục_hồi giấy_phép lái_xe căn_cứ luật tổ_chức phủ 19 6 2015 luật sửa_đổi bổ_sung luật tổ_chức phủ_luật tổ_chức quyền địa_phương 22 11 2019 căn_cứ luật xử_lý vi_phạm hành 20 6 2012 luật sửa_đổi bổ_sung luật xử_lý vi_phạm hành 15 11 2020 căn_cứ luật trật_tự an giao_thông đường_bộ 27 6 2024 đề_nghị bộ_trưởng bộ công_an phủ ban_hành nghị_định quy_định xử_phạt vi_phạm hành_trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ trừ phục_hồi giấy_phép lái_xe i quy_định chung 1 phạm_vi chỉnh 1 nghị_định quy_định a xử_phạt vi_phạm hành_trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ hành_vi vi_phạm hành_hình_thức mức xử_phạt biện_pháp khắc_phục hậu_quả đối_hành_vi vi_phạm hành_thẩm_quyền lập biên_bản thẩm_quyền xử_phạt mức phạt tiền cụ chức_danh đối_hành_vi vi_phạm hành_trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ b mức trừ giấy_phép lái_xe đối_hành_vi vi_phạm hành_trình_tự thủ_tục thẩm_quyền trừ phục_hồi giấy_phép lái_xe quản_lý chấp_hành pháp_luật trật_tự an giao_thông đường_bộ lái_xe 2 hành_vi vi_phạm hành lĩnh_vực quản_lý_nhà_nước liên_quan trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ quy_định nghị_định áp_dụng quy_định nghị_định quy_định xử_phạt vi_phạm hành lĩnh_vực xử_phạt 2 đối_tượng áp_dụng 1 cá_nhân tổ_chức việt_nam cá_nhân tổ_chức nước_ngoài hành_vi vi_phạm hành_trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ lãnh_thổ nước cộng_hòa xã_hội_chủ_nghĩa_việt_nam 2 tổ_chức quy_định 1,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
a cơ_quan nhà_nước hành_vi vi_phạm hành_vi nhiệm_vụ quản_lý_nhà_nước giao_b đơn_vị sự_nghiệp công_lập c tổ_chức_trị xã_hội tổ_chức_trị xã_hội nghề_nghiệp tổ_chức xã_hội tổ_chức xã_hội nghề_nghiệp d tổ_chức kinh_tế thành_lập quy_định luật doanh_nghiệp doanh_nghiệp tư_nhân công_ty cổ_phần công_ty trách_nhiệm hữu_hạn công_ty hợp_danh đơn_vị phụ doanh_nghiệp chi_nhánh văn_phòng đại_diện đ tổ_chức kinh_tế thành_lập quy_định luật hợp_tác_xã tổ_hợp_tác hợp_tác_xã liên_hiệp hợp_tác_xã e_cơ_sở đào_tạo lái_xe trung_tâm sát_hạch lái_xe cơ_sở đăng_kiểm xe_cơ_giới xe_máy chuyên_dùng cơ_sở thử_nghiệm sản_xuất lắp_ráp nhập_khẩu bảo_hành bảo_dưỡng xe_cơ_giới xe_máy chuyên_dùng g tổ_chức thành_lập quy_định pháp_luật h cơ_quan tổ_chức nước_ngoài cấp thẩm_quyền việt_nam phép hoạt_động lãnh_thổ việt_nam 3 hộ kinh_doanh hộ gia_đình thực_hiện hành_vi vi_phạm_hành quy_định nghị_định xử_phạt đối_cá_nhân vi_phạm 4 thẩm_quyền lập biên_bản vi_phạm hành_thẩm_quyền xử_phạt vi_phạm_hành tổ_chức cá_nhân liên_quan xử_phạt vi_phạm_hành quy_định nghị_định 5 thẩm_quyền trừ phục_hồi giấy_phép lái_xe 3 hình_thức xử_phạt vi_phạm hành_biện_pháp khắc_phục hậu_quả thu_hồi giấy_phép chứng hành_nghề 1 đối_hành_vi vi_phạm hành_trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ cá_nhân tổ_chức vi_phạm chịu hình_thức xử_phạt a cảnh_cáo b phạt tiền c_tịch_thu phương_tiện sử_dụng vi_phạm hành 2 căn_cứ tính_chất mức_độ vi_phạm cá_nhân tổ_chức vi_phạm hành_trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ áp_dụng hình_thức xử_phạt bổ_sung a_tước quyền sử_dụng giấy_phép chứng_hành_nghề thời_hạn b_đình hoạt_động thời_hạn c tịch_thu tang_vật vi_phạm hành_phương_tiện sử_dụng vi_phạm hành trường_hợp áp_dụng hình_thức xử_phạt quy_định c 1,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3 biện_pháp khắc_phục hậu_quả vi_phạm hành_trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ a_buộc khôi_phục tình_trạng ban_đầu thay_đổi vi_phạm hành gây trừ biện_pháp khắc_phục hậu_quả quy_định e_n p b buộc thực_hiện biện_pháp khắc_phục tình_trạng ô_nhiễm môi_trường vi_phạm_hành gây c buộc tái_xuất phương_tiện khỏi việt_nam d buộc nộp lợi bất_hợp_pháp thực_hiện vi_phạm hành đ buộc phá dỡ_vật che_khuất biển_báo_hiệu đường_bộ đèn tín_hiệu giao_thông e_buộc lắp đầy_đủ thiết thay_thiết đủ tiêu_chuẩn quy_chuẩn an kỹ_thuật khôi_phục tính_năng kỹ_thuật phương_tiện_thiết quy_định tháo bỏ thiết_lắp quy_định g buộc cấp thẻ nhận_dạng lái_xe lái_xe quy_định h_buộc tổ_chức tập_huấn hướng_dẫn nghiệp_vụ quy_trình tổ_chức khám sức khỏe_định_kỳ lái_xe nhân_viên phục_vụ xe quy_định i buộc lắp_đặt thiết_giám_sát hành_trình thiết ghi_nhận hình_ảnh lái_xe dây đai_an ghế_ngồi trẻ_em mầm_non học_sinh tiểu_học dụng_cụ thiết chuyên_dùng cứu_hộ hỗ_trợ cứu_hộ xe quy_định k_buộc tháo_dỡ thiết_âm_thanh ánh_sáng lắp_đặt xe gây mất trật_tự an giao_thông đường_bộ l buộc cung_cấp cập_nhật truyền dẫn lưu_trữ quản_lý thông_tin dữ_liệu thiết_giám_sát hành_trình thiết ghi_nhận hình_ảnh lái_xe lắp xe ô_tô quy_định m buộc chỉnh đồng_hồ báo quãng đường xe ô_tô làm sai_lệch n buộc khôi_phục nhãn_hiệu màu sơn ghi chứng_nhận đăng_ký xe quy_định o_buộc thực_hiện quy_định biển xe quy_định kẻ dán chữ biển thông_tin thành xe cửa xe quy_định màu sơn biển_báo dấu_hiệu nhận_biết xe p buộc khôi_phục hình_dáng kích_thước tình_trạng an kỹ_thuật ban_đầu xe đăng_kiểm đưa phương_tiện tham_gia giao_thông q buộc thực_hiện chỉnh thùng_xe quy_định hiện_hành đăng_kiểm_chỉnh khối_lượng hàng hóa_phép chuyên_chở ghi giấy chứng_nhận kiểm_định an kỹ_thuật bảo_vệ môi_trường quy_định hiện_hành đưa phương_tiện tham_gia giao_thông r buộc làm thủ_tục đổi thu_hồi cấp cấp chứng_nhận đăng_ký xe biển xe giấy chứng_nhận kiểm_định an kỹ_thuật bảo_vệ môi_trường quy_định s buộc nộp giấy_phép chứng_hành_nghề tẩy xóa sửa_chữa làm sai_lệch nội_dung t buộc đưa phương_tiện quay trở_khu kinh_tế thương_mại biệt_khu kinh_tế cửa_khẩu quốc_tế,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 thủ_tục thi_hành biện_pháp khắc_phục hậu_quả buộc nộp giấy_phép chứng_hành_nghề tẩy xóa sửa_chữa làm sai_lệch nội_dung thu_hồi giấy_phép chứng_hành_nghề giá_trị_sử_dụng cơ_quan thẩm_quyền cấp_a cá_nhân tổ_chức vi_phạm trách_nhiệm thi_hành biện_pháp khắc_phục hậu_quả buộc nộp giấy_phép chứng_hành_nghề tẩy xóa sửa_chữa làm sai_lệch nội_dung giấy_phép lái_xe chứng_nhận đăng_ký xe bản chứng_nhận đăng_ký xe chứng_thực kèm bản_gốc giấy biên_nhận tổ_chức tín_dụng chi_nhánh ngân_hàng nước_ngoài trường_hợp tổ_chức tín_dụng chi_nhánh ngân_hàng nước_ngoài giữ bản_gốc chứng_nhận đăng_ký xe giấy chứng_nhận tem kiểm_định an kỹ_thuật bảo_vệ môi_trường phương_tiện tẩy xóa sửa_chữa làm sai_lệch nội_dung thực_hiện quy_định 85 luật xử_lý vi_phạm hành_thẩm_quyền quyết_định thi_hành biện_pháp khắc_phục hậu_quả chuyển giấy_phép chứng_hành_nghề tẩy xóa sửa_chữa làm sai_lệch nội_dung cơ_quan thẩm_quyền cấp giấy_phép chứng_hành_nghề b đối giấy_phép chứng_hành_nghề giá_trị_sử_dụng cơ_quan thẩm_quyền cấp giấy_phép lái_xe cơ_quan thẩm_quyền cấp hợp_lệ phù_hiệu giấy_phép lưu_hành giá_trị_sử_dụng cơ_quan thẩm_quyền cấp hồ_sơ loại giấy_tờ tài_liệu tẩy_xóa sửa_chữa giả_mạo chứng_nhận đăng_ký xe bản chứng_nhận đăng_ký xe chứng_thực kèm bản_gốc giấy biên_nhận tổ_chức tín_dụng chi_nhánh ngân_hàng nước_ngoài trường_hợp tổ_chức tín_dụng chi_nhánh ngân_hàng nước_ngoài giữ bản_gốc chứng_nhận đăng_ký xe cơ_quan thẩm_quyền cấp khung động_cơ máy giấy chứng_nhận tem kiểm_định an kỹ_thuật bảo_vệ môi_trường cơ_quan thẩm_quyền cấp thẩm_quyền tạm giữ tiến_hành thu_hồi quy_định trường_hợp thẩm_quyền tạm giữ giấy_phép chứng_hành_nghề thẩm_quyền thu_hồi giấy_phép chứng_hành_nghề chuyển cơ_quan thẩm_quyền cấp loại giấy_tờ xử_lý quy_định pháp_luật trừ trường_hợp vụ dấu_hiệu tội_phạm thông_báo cá_nhân tổ_chức vi_phạm biết 4 thời_hiệu xử_phạt vi_phạm hành_hành_vi vi_phạm hành_kết_thúc hành_vi vi_phạm_hành thực_hiện 1 thời_hiệu xử_phạt vi_phạm hành_trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ 01 2 thời_hạn sử_dụng kết_quả thu_thập phương_tiện_thiết kỹ_thuật nghiệp_vụ phương_tiện_thiết kỹ_thuật cá_nhân tổ_chức cung_cấp xác_định cá_nhân tổ_chức vi_phạm tính thời phương_tiện_thiết kỹ_thuật nghiệp_vụ phương_tiện_thiết kỹ_thuật cá_nhân tổ_chức ghi_nhận kết_quả cuối thời_hiệu xử_phạt vi_phạm hành_đối_hành_vi vi_phạm quy_định 1 6 luật xử_lý vi_phạm_hành thời_hạn nêu thẩm_quyền quyết_định xử_phạt quy_định kết_quả thu_thập phương_tiện_thiết kỹ_thuật nghiệp_vụ phương_tiện_thiết kỹ_thuật cá_nhân tổ_chức cung_cấp giá_trị_sử_dụng trường_hợp cá_nhân tổ_chức cố_tình trốn_tránh cản_trở xử_phạt thời_hạn sử_dụng kết_quả thu_thập phương_tiện_thiết kỹ_thuật nghiệp_vụ phương_tiện_thiết kỹ_thuật cá_nhân tổ_chức cung_cấp_tính kể thời chấm_dứt hành_vi trốn_tránh cản_trở xử_phạt,0.032003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3 hành_vi vi_phạm hành_kết_thúc hành_vi vi_phạm_hành thực_hiện a xác_định hành_vi vi_phạm hành_kết_thúc hành_vi vi_phạm_hành thực_hiện tính thời_hiệu xử_phạt vi_phạm_hành thực_hiện quy_định pháp_luật xử_lý vi_phạm hành_b đối_hành_vi vi_phạm phát_hiện thông phương_tiện_thiết kỹ_thuật nghiệp_vụ phương_tiện_thiết kỹ_thuật cá_nhân tổ_chức cung_cấp thời chấm_dứt hành_vi vi_phạm tính thời phương_tiện_thiết kỹ_thuật nghiệp_vụ phương_tiện_thiết kỹ_thuật ghi_nhận hành_vi vi_phạm 5 tước quyền sử_dụng giấy_phép chứng_hành_nghề thời_hạn 1 giấy_phép chứng_hành_nghề tước quyền sử_dụng thời_hạn nghị_định_a phù_hiệu cấp xe ô_tô tham_gia kinh_doanh vận_tải b giấy chứng_nhận tem kiểm_định an kỹ_thuật bảo_vệ môi_trường c giấy_phép đào_tạo lái_xe d giấy_phép sát_hạch đ giấy chứng_nhận đủ kiện hoạt_động kiểm_định xe_cơ_giới e_chứng đăng_kiểm_viên g giấy_phép lái_xe quốc_gia giấy_phép lái_xe quốc_tế nước tham_gia công_ước liên_hợp_quốc giao_thông đường_bộ 1968 cấp trừ giấy_phép lái_xe quốc_tế việt_nam cấp giấy_phép lái_xe quốc_tế việt_nam ký_kết_ước quốc_tế công_nhận lẫn nhau giấy_phép lái_xe quốc_tế 2 trình_tự thủ_tục tước quyền sử_dụng giấy_phép chứng_hành_nghề thời_hạn trật_tự an giao_thông lĩnh_vực giao_thông đường_bộ thực_hiện quy_định pháp_luật xử_lý vi_phạm hành trường_hợp cá_nhân thực_hiện hành_vi vi_phạm hành_xử_phạt lần phạt tiền đối_hành_vi vi_phạm hành_vi vi_phạm tước quyền sử_dụng giấy_phép lái_xe hành_vi vi_phạm trừ giấy_phép lái_xe áp_dụng hình_thức tước quyền sử_dụng giấy_phép lái_xe 3 thời bắt_đầu tính thời_hạn tước quyền sử_dụng giấy_phép chứng_hành_nghề a trường_hợp thời quyết_định xử_phạt vi_phạm hành_thẩm_quyền xử_phạt tạm giữ giấy_phép chứng hành_nghề cá_nhân tổ_chức vi_phạm thời bắt_đầu tính thời_hạn tước quyền sử_dụng giấy_phép chứng_hành_nghề thời quyết_định xử_phạt vi_phạm hành_hiệu_lực thi_hành b trường_hợp thời quyết_định xử_phạt vi_phạm hành_thẩm_quyền xử_phạt tạm giữ giấy_phép chứng hành_nghề cá_nhân tổ_chức vi_phạm thẩm_quyền xử_phạt quyết_định xử_phạt vi_phạm_hành quy_định đối_hành_vi vi_phạm nội_dung quyết_định xử_phạt ghi rõ thời bắt_đầu tính hiệu_lực thi_hành hình_thức xử_phạt bổ_sung tước quyền sử_dụng giấy_phép chứng_hành_nghề kể thời vi_phạm xuất_trình giấy_phép chứng_hành_nghề thẩm_quyền xử_phạt tạm giữ,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
csv_path = project_root / "data" / "processed" / "tfidf_matrix.csv"
df.to_csv(csv_path, index=False, encoding='utf-8-sig')
print(f"Đã lưu file CSV tại: {csv_path}")

Đã lưu file CSV tại: C:\study\2nd-4y\KHDL\code\Traffic_Law_Chatbot\data\processed\tfidf_matrix.csv

In [18]:
csv_path = project_root / "data" / "processed" / "tfidf_matrix_2.csv"
df.to_csv(csv_path, index=False, encoding='utf-8-sig')
print(f"Đã lưu file CSV tại: {csv_path}")

Đã lưu file CSV tại: C:\study\2nd-4y\KHDL\code\Traffic_Law_Chatbot\data\processed\tfidf_matrix_2.csv